### ISSUE TITLE
Propoarse error when parsing comment ending with tilde (~)

### ISSUE THREAD

**Issue by DanielBaciu** [consultingwerk/proparse#35]
Hi,

We have second error on propoarse when in a file we have a `~` as a last character in a comment.

`or iAscii eq 126 // ~`

If I drop the `~` or add a space after , the source is parsed alright.

We are using proparse.net, Version=4.1.0.1200.

![image](https://user-images.githubusercontent.com/79142425/108075739-600dd000-7073-11eb-9971-ad264e3b3ef3.png)

Complete call stack and error is:

```
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       Original Exception: expecting THEN, found 'else'
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg      
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       c:\ws\dev\11.7relatief\verkoop/common-email-logic.i:174:3: expecting THEN, found 'else'
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at antlr.Parser.match(Parser.java:211)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.ProParser.ifstate(ProParser.java:9621)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.ProParser.statement(ProParser.java:2810)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.ProParser.blockorstate(ProParser.java:560)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.ProParser.code_block(ProParser.java:586)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.ProParser.dostate(ProParser.java:3461)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.ProParser.labeled_block(ProParser.java:779)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.ProParser.blockorstate(ProParser.java:224)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.ProParser.code_block(ProParser.java:586)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.ProParser.functionstate(ProParser.java:9113)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.ProParser.statement(ProParser.java:2775)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.ProParser.blockorstate(ProParser.java:560)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.ProParser.program(ProParser.java:120)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at com.joanju.proparse.DoParse.doParse(DoParse.java:202)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:270)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:226)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:348)
[21/02/16@11:08:49.210+0200] P-068656 T-077884 1 4GL AnlzProg       at cli.Progress.ClrBridge.ClrApi.InvokeMethod(Unknown Source)
[21/02/16@11:08:49.211+0200] P-068656 T-077884 1 4GL AnlzProg       antlr.MismatchedTokenException: Mismatched Token

```
Thank you for checking,
Daniel Baciu.

**Comment by mikefechner** [comment]
Closing this issue here. There's a duplicate issue at

https://jira.consultingwerkcloud.com/browse/SCLSUP-350
