### ISSUE TITLE
Issue with database trigger block

### ISSUE THREAD

**Issue by DanielBaciu** [consultingwerk/proparse#45]
A database trigger block is not recognized well by Proparse.

Here is an example:
on write of order new bufNewOrder old bufOldOrder
do:
end.  

Error:
`trigger.p:5:19: unexpected token: new`

**Comment by mikefechner** [comment]
Please attach the complete class file as a repro and indicate the version of Proparse you are using. 

Are you intending to fix this and issue a pull-request?

**Comment by DanielBaciu** [comment]
I'm using proparse.dll version 4.1.0.1219.
Please fix it if possible.

The complete error stack is:
Original Exception: unexpected token: new                                          
                                                                                   
\trigger.p:5:19: unexpected token: new     
	at com.joanju.proparse.ProParser.exprt2(ProParser.java:20364)                    
	at com.joanju.proparse.ProParser.exprt(ProParser.java:16783)                     
	at com.joanju.proparse.ProParser.unaryExpression(ProParser.java:19770)           
	at com.joanju.proparse.ProParser.multiplicativeExpression(ProParser.java:19672)  
	at com.joanju.proparse.ProParser.additiveExpression(ProParser.java:19619)        
	at com.joanju.proparse.ProParser.relationalExpression(ProParser.java:19444)      
	at com.joanju.proparse.ProParser.notExpression(ProParser.java:19415)             
	at com.joanju.proparse.ProParser.andExpression(ProParser.java:19372)             
	at com.joanju.proparse.ProParser.orExpression(ProParser.java:19339)              
	at com.joanju.proparse.ProParser.xorExpression(ProParser.java:19306)             
	at com.joanju.proparse.ProParser.expression(ProParser.java:3406)                 
	at com.joanju.proparse.ProParser.expression_statement(ProParser.java:2358)       
	at com.joanju.proparse.ProParser.blockorstate(ProParser.java:564)                
	at com.joanju.proparse.ProParser.onstate(ProParser.java:10796)                   
	at com.joanju.proparse.ProParser.statement(ProParser.java:2894)                  
	at com.joanju.proparse.ProParser.blockorstate(ProParser.java:560)                
	at com.joanju.proparse.ProParser.program(ProParser.java:120)                     
	at com.joanju.proparse.DoParse.doParse(DoParse.java:205)                         
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:270)                
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:226)                
	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:348)         
	at cli.Progress.ClrBridge.ClrApi.InvokeMethod(Unknown Source)                    

[trigger.zip](https://github.com/consultingwerk/proparse/files/6980495/trigger.zip)

**Comment by mikefechner** [comment]
All can be fixed ;) It's just a matter of time and resources. 

This is an open-source project. We will accept pull requests from the community.

**Comment by DanielBaciu** [comment]
I have few more. will log them all and I will see if we can fix any of these.
