### ISSUE TITLE
Issue with extent function on class property

### ISSUE THREAD

**Issue by DanielBaciu** [consultingwerk/proparse#46]
We have a class with a property with few extents. The code calling extent function on object property is not parsing. 

The error I get is:
`..client.p:3:26: unexpected token: (`

Code to reproduce:

class ClassWithExtentProp: 
  define public property pProperty as character  no-undo extent public get. public set.
end class.

client.p
  define variable oObj   as ClassWithExtentProp no-undo.
  define variable iCount as integer             no-undo.
  do iCount = 1 to extent(oObj:pProperty):
  end.

Thank you for checking.

**Comment by mikefechner** [comment]
Please attach the complete class file as a repro and indicate the version of Proparse you are using.

Are you intending to fix this and issue a pull-request?

**Comment by DanielBaciu** [comment]
I'm using proparse.dll version 4.1.0.1219.
Please fix it if possible.

The complete error stack is:

                                                                                             
Original Exception: unexpected token: (                                                      
                                                                                             
C:\Analiza\Parse issue 4_extent\proparseExtentPropError.p:22:26: unexpected token: (         
  at com.joanju.proparse.ProParser.block_opt(ProParser.java:3862)                            
  at com.joanju.proparse.ProParser.dostate(ProParser.java:3450)                              
  at com.joanju.proparse.ProParser.statement(ProParser.java:2698)                            
  at com.joanju.proparse.ProParser.blockorstate(ProParser.java:560)                          
  at com.joanju.proparse.ProParser.program(ProParser.java:120)                               
  at com.joanju.proparse.DoParse.doParse(DoParse.java:202)                                   
  at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:270)                          
  at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:226)                          
  at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:348)                   
  at cli.Progress.ClrBridge.ClrApi.InvokeMethod(Unknown Source)                              

[extent.zip](https://github.com/consultingwerk/proparse/files/6980472/extent.zip)
