### ISSUE TITLE
Issues with PROCESS-ARCHITECTURE

### ISSUE THREAD

**Issue by DanielBaciu** [consultingwerk/proparse#49]
We are using PROCESS-ARCHITECTURE to decide the type of variable we use to communicate with external dll. 

I reduce the code to reproduce the error to the following:

&IF PROCESS-ARCHITECTURE EQ 32 &THEN
  &GLOBAL-DEFINE PTRSIZE                4
  &GLOBAL-DEFINE PTR                    LONG
&ELSEIF PROCESS-ARCHITECTURE EQ 64 &THEN
  &GLOBAL-DEFINE PTRSIZE                8
  &GLOBAL-DEFINE PTR                    INT64
&ENDIF

DEF VAR iCallbackModuleHandle  AS {&DEF_PTR}      NO-UNDO INIT 0.

Thank you for checking.

**Comment by mikefechner** [comment]
Any issue with that? Please report an error message when there is one. Please indicate which Proparse release you are using.

Are you intending to fix this yourself and issue a pull-request?

**Comment by DanielBaciu** [comment]
I'm using proparse.dll version 4.1.0.1219.
Please fix it if possible.

The complete error stack is:
T-098224 1 4GL -- No entry types are activated
T-098224 1 4GL PsrHelp        Error parsing VarAsPreproc.p
T-098224 1 4GL PsrHelp        
T-098224 1 4GL PsrHelp        Original Exception: <AST>:0:0: unexpected AST node: Field_ref "" :0:0
T-098224 1 4GL PsrHelp        
T-098224 1 4GL PsrHelp        java.lang.RuntimeException: <AST>:0:0: unexpected AST node: Field_ref "" :0:0
T-098224 1 4GL PsrHelp          at com.joanju.proparse.Postlexer.nextToken(Postlexer.java:81)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.Postlexer.<bridge>nextToken(Postlexer.java:1)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.TokenList.build(TokenList.java:37)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.DoParse.doParse(DoParse.java:146)
T-098224 1 4GL PsrHelp          at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:270)
T-098224 1 4GL PsrHelp          at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:226)
T-098224 1 4GL PsrHelp          at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:348)
T-098224 1 4GL PsrHelp          at cli.Progress.ClrBridge.ClrApi.InvokeMethod(Unknown Source)
T-098224 1 4GL PsrHelp        Caused by: <AST>:0:0: unexpected AST node: Field_ref "" :0:0
T-098224 1 4GL PsrHelp          at com.joanju.proparse.ProEval.expr(ProEval.java:178)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.ProEval.comparisonop(ProEval.java:499)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.ProEval.expr(ProEval.java:91)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.ProEval.preproIfEval(ProEval.java:32)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.DoParse.doParse(DoParse.java:200)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.DoParse.doParse(DoParse.java:108)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.Postlexer.preproIfCond(Postlexer.java:301)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.Postlexer.preproIf(Postlexer.java:172)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.Postlexer.nextToken(Postlexer.java:53)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.Postlexer.<bridge>nextToken(Postlexer.java:1)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.TokenList.build(TokenList.java:37)
T-098224 1 4GL PsrHelp          at com.joanju.proparse.DoParse.doParse(DoParse.java:147)
T-098224 1 4GL PsrHelp          at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:271)
T-098224 1 4GL PsrHelp          ... 3 more


[PROCESS-ARCHITECTURE.zip](https://github.com/consultingwerk/proparse/files/6980440/PROCESS-ARCHITECTURE.zip)
