### ISSUE TITLE
Buffer parameter for buffer 

### ISSUE THREAD

**Issue by DanielBaciu** [consultingwerk/proparse#50]
Although is not best practice, we have the following piece of code which is compiling but is not supported by proparse. 

define buffer bufCustomer for Customer.

function CreatieLijst returns logical private
  ( BUFFER pbufCustomer for bufCustomer):
  return true.
end function.

`Original Exception: null`

Thank you for checking.

**Comment by mikefechner** [comment]
Please include the complete error message (no error message is complete without stack-trace). Please indicate which Proparse release you are using.

Are you intending to fix this yourself and issue a pull request?

**Comment by DanielBaciu** [comment]
I'm using proparse.dll version 4.1.0.1219. 
The complete error stack is:



[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        Original Exception: null

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        java.lang.NullPointerException

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at com.joanju.proparse.SymbolScope.defBuffer(SymbolScope.java:76)

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at com.joanju.proparse.ParserSupport.defBuffer(ParserSupport.java:114)

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at com.joanju.proparse.ProParser.function_param(ProParser.java:44140)

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at com.joanju.proparse.ProParser.function_params(ProParser.java:32566)

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at com.joanju.proparse.ProParser.functionstate(ProParser.java:9048)

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at com.joanju.proparse.ProParser.statement(ProParser.java:2775)

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at com.joanju.proparse.ProParser.blockorstate(ProParser.java:560)

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at com.joanju.proparse.ProParser.program(ProParser.java:120)

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at com.joanju.proparse.DoParse.doParse(DoParse.java:202)

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:270)

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:226)

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:348)

[21/08/11@12:04:43.665+0300] P-075816 T-070124 1 4GL PsrHelp        	at cli.Progress.ClrBridge.ClrApi.InvokeMethod(Unknown Source)

[bufferproparse.p.txt](https://github.com/consultingwerk/proparse/files/6980417/bufferproparse.p.txt)

[bufferproparse.log](https://github.com/consultingwerk/proparse/files/6980412/bufferproparse.log)
