### ISSUE TITLE
Double quotes in preprocessor parameters of include

### ISSUE THREAD

**Issue by DanielBaciu** [consultingwerk/proparse#51]
In our framework we have a set of includes building up a browser in chui. I attached a subset to reproduce one error we have. 
My proparse.dll version is 4.1.0.1219.

[DoubleQuotes.zip](https://github.com/consultingwerk/proparse/files/6980801/DoubleQuotes.zip)

Example:
_example.p_
{browse.i
    &bform="
            customer.name         column-label ""Name""  format ""x(16)"" 
            with 12 down row 5 centered overlay"
}

_browse.i_
{ browser.i
  {&*}
  &bform = "with 12 down row 5 centered overlay "
  &rep-add = "down. "
  &bframe = brw{&seq}
}

_browser.i_
form {&bform} {{&bformf}{&*}}
     frame {&bframe}.                                /* BROWSE frame */

Error:

Original Exception: unexpected token: Name

c:\ws\dev\11.7relatief\lib/browser.i:185:6: unexpected token: Name
  at com.joanju.proparse.ProParser.constant(ProParser.java:4280)
  at com.joanju.proparse.ProParser.label_constant(ProParser.java:28307)
  at com.joanju.proparse.ProParser.format_opt(ProParser.java:42823)
  at com.joanju.proparse.ProParser.formatphrase(ProParser.java:42160)
  at com.joanju.proparse.ProParser.form_item(ProParser.java:42028)
  at com.joanju.proparse.ProParser.form_items_or_record(ProParser.java:38860)
  at com.joanju.proparse.ProParser.formstate(ProParser.java:8861)
  at com.joanju.proparse.ProParser.statement(ProParser.java:2768)
  at com.joanju.proparse.ProParser.blockorstate(ProParser.java:560)
  at com.joanju.proparse.ProParser.program(ProParser.java:120)
  at com.joanju.proparse.DoParse.doParse(DoParse.java:205)
  at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:270)
  at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:226)
  at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:348)
  at cli.Progress.ClrBridge.ClrApi.InvokeMethod(Unknown Source)

**Comment by DanielBaciu** [comment]
What I also observed is that in my case we have two include levels. if we have only one level no error is reported by proparse.
