### ISSUE TITLE
Issue with block label

### ISSUE THREAD

**Issue by DanielBaciu** [consultingwerk/proparse#52]
When there is a preprocessor between block level and block itself poparse generates an error. 

_Code:_ 
   ROUTE-BLOCK:
  {&_proparse_ prolint-nowarn(use-index)}
  do:
	.
  end.

 Error parsing blockLabel.p                                                                      
                                                                                                 
 Original Exception: unexpected token:  ROUTE-BLOCK                                            
                                                                                                 
 C:\Analiza\Parse issue 15_bloc_label\blockLabel.p:2:3: unexpected token:  ROUTE-BLOCK
         
   at com.joanju.proparse.ProParser.blockorstate(ProParser.java:568)                             
   at com.joanju.proparse.ProParser.program(ProParser.java:120)                                  
   at com.joanju.proparse.DoParse.doParse(DoParse.java:202)                                      
   at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:270)                             
   at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:226)                             
   at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:348)                      
   at cli.Progress.ClrBridge.ClrApi.InvokeMethod(Unknown Source)                                 

[blockLabel.zip](https://github.com/consultingwerk/proparse/files/6981194/blockLabel.zip)

**Comment by mikefechner** [comment]
What is the purpose of _anything_ between the block label and the block?

We won't spend time for purely academical syntax constructs.

**Comment by DanielBaciu** [comment]
Whet we have between label and block is a prolint directive, which needs to be just before _for each_ block. 

Here is the code we used:
```
 ToteRoute_Loop:
  {&_proparse_ prolint-nowarn(use-index)}
  for each bfRunnoToteLink
```

On compile time this directive is empty resulting an empty line between.

**Comment by gquerret** [comment]
@DanielBaciu Note that this issue (and the other ones that have been reported the same day) are already fixed in the [sonar-openedge](https://github.com/Riverside-Software/sonar-openedge) implementation of Proparse.
