### ISSUE TITLE
dynamic-property function is not (properly) handled

### ISSUE THREAD

**Issue by skepsys82** [consultingwerk/proparse#60]
following code is not properly handled by proparse:

clsBE = dynamic-property(cClassName, "instance").

Error stack:
org.prorefactor.refactor.RefactorException: Error parsing SI.p

Original Exception: unexpected token: (

...\AppServer\src\ServiceInterface\SI.p:74:28: unexpected token: (
	at com.joanju.proparse.ProParser.assignstate2(ProParser.java:2094)
	at com.joanju.proparse.ProParser.blockorstate(ProParser.java:425)
	at com.joanju.proparse.ProParser.code_block(ProParser.java:587)
	at com.joanju.proparse.ProParser.procedurestate(ProParser.java:11419)
	at com.joanju.proparse.ProParser.statement(ProParser.java:2979)
	at com.joanju.proparse.ProParser.blockorstate(ProParser.java:561)
	at com.joanju.proparse.ProParser.program(ProParser.java:121)
	at com.joanju.proparse.DoParse.doParse(DoParse.java:203)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:271)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:226)
	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:348)
	at cli.Progress.ClrBridge.ClrApi.InvokeMethod(Unknown Source)
	at cli.Progress.ClrBridge.BrgClrToPro.runEventDispatcher(Unknown Source)
	at cli.Progress.ClrBridge.ClrApi$ProgressMessageFilter.PreFilterMessage(Unknown Source)
	at cli.System.Windows.Forms.Application$ThreadContext.ProcessFilters(Unknown Source)
	at cli.System.Windows.Forms.Application$ThreadContext.PreTranslateMessage(Unknown Source)
	at cli.System.Windows.Forms.Application$ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Unknown Source)
	at cli.System.Windows.Forms.Application$ThreadContext.RunMessageLoopInner(Unknown Source)
	at cli.System.Windows.Forms.Application$ThreadContext.RunMessageLoop(Unknown Source)
	at cli.Progress.ClrBridge.ClrApi.InvokeMethod(Unknown Source)

antlr.NoViableAltException: NoViableAlt

**Comment by mikefechner** [comment]
Looks like DYNAMIC-PROPERTY is not yet part of the Proparse grammar at all. Are you able to add support for this and issue a pull request?
